### ISSUE TITLE
Insert image/table popup always shows up when text cursor is active

### ISSUE THREAD

**Issue by viktorix** [ClassicPress-research/ClassicPress-Editor#14]
When I try to create a post/page, I click on the empty text editor to begin writing and the image/table popup shows up. It disappears when I type. It seems to only show up at the beginning of the new paragraph.

![image](https://user-images.githubusercontent.com/1692600/131283213-70ee4311-1c37-4d8f-87fb-d7c0bd36d063.png)

**Comment by johnalarcon** [comment]
Yeah, I also found that annoying.

**Comment by simplycomputing** [comment]
Me too!

**Comment by johnalarcon** [comment]
I've resolved this issue.

![image](https://user-images.githubusercontent.com/12477319/131375514-ead83f6b-1745-4279-922f-e0fc95cae384.png)

...additionally, a dialog was floating when you selected things in the editor; I've also nixed it with this change.

![image](https://user-images.githubusercontent.com/12477319/131374970-1dd26547-6b7c-4bf7-b76a-5f20b8fa47a0.png)

[See the changes here](https://github.com/ClassicPress-research/ClassicPress-Editor/blob/2b1d23bba4be14a4ba821326b01efd8cfd176f63/scripts/classicpress-editor.js#L14-L15)

For reference: these little dialogs are known as "quickbars".

**Comment by arjayarana** [comment]
@johnalarcon I've installed the latest version of the editor, but in my browser (Microsoft Edge) only one of the quickbars is gone. The selection quickbar still shows up when I select text. I've checked the javascript file, and your two fixes are still there.

Since this editor is coded in javascript, which is processed on the client side, maybe the problem lies with the browser being used? Just like with the overlay for text mode / source code. In your FF browser it renders okay. Mine it does not.

**Comment by simplycomputing** [comment]
Yes. Just tested in Edge and the quickbar that comes up when you select some text is still there for me too. Same in Brave (aka Chrome).

**Comment by johnalarcon** [comment]
Thanks for the report and confirmation. This is resolved on the main branch.

**Comment by viktorix** [comment]
Yes, fixed now. Thanks.
