### ISSUE TITLE
Word count doesn't work

### ISSUE THREAD

**Issue by viktorix** [ClassicPress-research/ClassicPress-Editor#15]
Word count that comes with TinyMCE works, but the one that WordPress includes doesn't.

![image](https://user-images.githubusercontent.com/1692600/131283727-c0793f37-26b7-4f2e-bfb5-7157ff8f33b6.png)

**Comment by johnalarcon** [comment]
This is to be expected since that's a v4 feature. It's likely that we can keep the new word count and remove the old one.

**Comment by simplycomputing** [comment]
Yes, using word count in the tools menu works fine.
![word-count](https://user-images.githubusercontent.com/46998578/131293054-c4f58925-ebc3-4c90-9176-8625673ecc59.png)

**Comment by arjayarana** [comment]
Mine is working, but inaccurately. The menu says 485.

![word-count](https://user-images.githubusercontent.com/89768197/131309298-6aeed7e8-ff0d-4f33-b1fc-26a8bb6e1a17.png)

@viktorix Maybe this has something to do with post status? Mine was already published. Yours was still draft.

**Comment by arjayarana** [comment]
Mine is working, but inaccurately. The menu says 485.

![word-count](https://user-images.githubusercontent.com/89768197/131309298-6aeed7e8-ff0d-4f33-b1fc-26a8bb6e1a17.png)

@viktorix Maybe this has something to do with post status? Mine was already published. Yours was still draft.

**Comment by johnalarcon** [comment]
This won't be related to post status. I haven't tested this at all, but, am thinking that the new word counts (at lower-right of the editor and also under the Tools menu) are going to be the accurate ones since the other word count (at lower left) was to support the v4 editor. It will likely be removed/replaced with the newer counter.

**Comment by johnalarcon** [comment]
I've hidden the CP word count (at lower left) with plain CSS to get it out of view until it can be removed/replaced. Note that the new counter (at lower right) can be clicked to toggle between **total words** and **total characters**. It _may_ behoove us to move the counter to the other side where people have grown accustomed to finding it. Since the counter _is_ actually working, I'm closing this issue.

[See the code change here](https://github.com/ClassicPress-research/ClassicPress-Editor/commit/3a548d1dd0476c55f2d874f7953c32a06fc981df)
