### ISSUE TITLE
Implement plugin - directionality

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress-research/ClassicPress-Editor#33]
### Implement `directionality` TinyMCE plugin

The various controls and behaviors of the v4 plugin currently included in ClassicPress should be reasonably replicated by the v5 editor, or by the updated TinyMCE core. Prior to testing, install the [ClassicPress Editor](https://github.com/ClassicPress-research/ClassicPress-Editor/archive/refs/heads/main.zip) plugin. **Do not activate it.** If the plugin is already installed, be sure to deactivate it before starting your tests.

#### Testing Notes
```
1. Click to edit any post with the built-in editor.
2. Switch between ltr an rtl modes.
3. Save the post.
4. Activate the new Classic Editor plugin.
5. Click to edit the same post.
6. Verify that the new editor replicates the expected behavior.
```

This issue has a corresponding item on the Task List in issue #2.

**Comment by joyously** [comment]
In my test, the button does not show up unless you are in RLT, since the button is for making something LTR.
Install the [RTL Tester](https://wordpress.org/plugins/rtl-tester/) plugin. 
### Testing steps
Edit a page/post.
See that there is no button for LTR on the toolbar.
Activate the RTL Tester plugin.
Edit a page/post.
Position the cursor on some text like paragraph or heading.
Use the LTR button to toggle that text between RTL and LTR. When you move the cursor to other text, the button should indicate the directionality state of the text.

Repeat these steps with the new editor plugin.

**Comment by joyously** [comment]
I'm wondering if the 4.x plugin is broken since the RTL button does not show, but it is in the code.

There seems to be a problem with the 5.x directionality plugin.
It inserts the `dir="ltr"` attribute, but does not remove it. It uses the new ToggleButton instead of a plain button.
It also does not show the RTL button.

**Comment by joyously** [comment]
I tried the LTR and RTL buttons on the skin creator site. Even though the code indicates that these are toggle buttons, they are not. Each one indicates the direction of the text and to use either one, you need to have both buttons, so you can choose the opposite direction from what you have.

There are two 4.x buttons, which actually are toggles. You could use just one button and it worked.
With 5.x, you need both buttons, because neither one toggles. They both just put the chosen direction into the HTML.

I see two choices.
1. Use the 5.x buttons as they are, always putting both on the toolbar.
2. Modify the 4.x code to work with 5.x, which is adding a small function for the `stateselector` context that was removed.
