### ISSUE TITLE
Right-clicking anywhere in the editor makes the hyperlink dialog appear

### ISSUE THREAD

**Issue by KTS915** [ClassicPress-research/ClassicPress-Editor#77]
**Describe the bug**
Right-clicking anywhere in the editor makes the hyperlink dialog appear

**To Reproduce**
1. Right-click anywhere in the editor
2. See error hyperlink dialog appear

**Expected behavior**
I would expect the dialog to appear when right-clicking only if I had first selected some text

**Desktop (please complete the following information):**
 -  OS: Linux Mint 20.2 Cinnamon
 -  Browser Firefox 94.0
 -  Version 1.0.22

**Comment by joyously** [comment]
This is temporary. The `link` plugin defines it that way. We are using the `link` plugin until I get the `wplink` plugin working. (I was looking at it again last night, and I still don't understand contextforms enough to make it go.)

**Comment by joyously** [comment]
To explain more completely, the [docs](https://www.tiny.cloud/docs/configure/editor-appearance/#contextmenu) say
> The default configuration includes the context menu sections for the following plugins: link, linkchecker , image, imagetools, permanentpen, table, and spellchecker.

Out of this default list, only the link plugin is being loaded (which is temporary), so that is what you get for the context menu. It also says
> Note: When the TinyMCE context menu is enabled, users can still access the browser context menu, including the browser spellchecker, using the `Ctrl+Right` click shortcut.

Perhaps it would be better to set it to `false`. I don't know if this changed since the WP integration, but trying it in 4.x I get the browser context menu.

**Comment by KTS915** [comment]
I am not sure what is gained by having such a context menu. So I would be inclined to set it to false.
